def print_car():
    print("     |          ||           |")
    print("     |          ||           |")
    print("     |          ||           |")
    print("      ______________________")
    print("     \\____________________/")
    print("    __/  |____________|  \\__")
    print("        /00__________00\\")
    print("     |___/___GTR-R34___\\___|")
    print("       \\OO_|__|__|__|_OO/")
    print("     |____|           |____|")
    print("  |          ||          |")
    print("  |          ||          |")
    print(" |          ||          |")
    print(" |          ||          |")
    print("|          ||          |")
    print("|          ||          |")

print_car()